### ISSUE TITLE
What's the correct connection string for Service Bus Queues?

### ISSUE THREAD

**Issue by richbleeker** [spotteron/enqueue-azure#13]
Hopefully a quick and easy one for the intelligent ones out there! I've tried many variations of the conn string, based on the examples in the docs... but keep getting cURL errors.

In Azure Portal, under my Service Bus config, I have created a namespace, and below that a single queue. I'm successfully sending messages to my queue from another app, but am now wanting to build a PHP app to receive and process messages off the queue.

In my Service Bus Namespace in Azure, if I go to Shared Access Policies, there's a single policy listed there, which when I click that it gives me a Primary Connection String as below:

Endpoint=sb://MyNameSpace.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XyzSecretInfo12345=

How does this translate to the example conn string of:

$factory = new AzureStorageConnectionFactory('DefaultEndpointsProtocol=https;AccountName=<accountname>;AccountKey=<youraccountkey>');

**Comment by jwaguet** [comment]
Hi @richbleeker ,
you can have a look at the documentation of our bundle : https://github.com/assoconnect/phpenqueue-azure-service-bus

You can create your context of Azure service bus like that : 

```php
<?php
use WindowsAzure\Common\ServicesBuilder;

// connects to azure
$connectionString = "Endpoint=[yourEndpoint];SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=[Primary Key]";

$serviceBusRestProxy = ServicesBuilder::getInstance()->createServiceBusService($connectionString);

$context = $factory->createContext();
```

**Comment by richbleeker** [comment]
Thanks – I’ve managed to connect now!

Next question – is there a known way to asynchronously wait for messages from Service Bus Queues in PHP? Everywhere I’ve seen is using long-polling to the REST endpoint. I’d prefer a method which keeps a socket open to Service Bus, and calls an event handler / closure when a message is received off the queue. I’ve seen that Service Bus supports AMQP but haven’t been able to connect to SB using any AMQP PHP libraries…

**Comment by sylfabre** [comment]
@richbleeker I don't know about this async wait.

I'm closing this issue as your initial problem is solved
