### ISSUE TITLE
Receiving base64 encoded messages

### ISSUE THREAD

**Issue by NavyCoat** [spotteron/enqueue-azure#3]
Hi,

When I push to my queue any content, I always receive it encoded in base64.

I found in AzureStorageProducer:
```
        // Encoding of msg body as azure expect it
        if ($encode === true) {
            $messageBody = base64_encode($messageBody);
        }
```

I can't find anything about encoding content for azure. Also, I didn't notice any decoding later.
Can you fix it, or provide more information about why it have to be encoded for azure? Maybe i find some time for do something with that.

And thanks for the package :)

**Comment by PaulRouss3l** [comment]
Hello @NavyCoat !

Yes, as Azure, by default, expect a base64 encoded body we had to do so. We want to keep this encoding to remain compliant both with Azure services and Interop.

You're right, we need to had a base64_decode(); in src\AzureStorageConsumer.php

I'll update it

**Comment by NavyCoat** [comment]
Hey @PaulRouss3l, when can I expect a release of #3 and #4?
