### ISSUE TITLE
Upgrade queue-interop dependency

### ISSUE THREAD

**Issue by TiS** [spotteron/enqueue-azure#5]
Required queue-interop version is locked on 0.7, which collides with some other components. Please, add support for queue-interop 0.8.

**Comment by sylfabre** [comment]
Would you like to work on a PR for this?

**Comment by sylfabre** [comment]
@TiS Would you like to work on a PR for this?

**Comment by TiS** [comment]
As I see that, you ran your tests on queue-interop@master, and they passed. Thus there shouldn't be any problems, it's a simple composer.json change.

**Comment by TiS** [comment]
Ok, this is not so somple, give me some time to refactor my PR.

**Comment by TiS** [comment]
I have checked the code and did not found any incompatibilities. The tests also run fine for 0.8 version.

**Comment by sylfabre** [comment]
@TiS could you please submit your PR?

**Comment by TiS** [comment]
Yes, sorry. Messed up :)

**Comment by TiS** [comment]
BTW - i think, that you travis file may have some problems. It failed on "sonar-scanner not found".
